"""empty message

Revision ID: 597389a39047
Revises: 55d4fe1d571d
Create Date: 2016-12-11 23:09:38.448491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597389a39047'
down_revision = '55d4fe1d571d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('isActive', sa.Boolean(), nullable=True))
    op.add_column('ideas', sa.Column('filePath', sa.String(length=100), nullable=True))
    op.add_column('roles', sa.Column('isActive', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('isActive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isActive')
    op.drop_column('roles', 'isActive')
    op.drop_column('ideas', 'filePath')
    op.drop_column('comments', 'isActive')
    # ### end Alembic commands ###
