"""empty message

Revision ID: b549b62155f9
Revises: 597389a39047
Create Date: 2016-12-12 23:34:13.021590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b549b62155f9'
down_revision = '597389a39047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('filename', sa.String(length=50), nullable=True))
    op.add_column('ideas', sa.Column('usability', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('ideas', 'usability')
    op.drop_column('ideas', 'filename')
    # ### end Alembic commands ###
